### PR TITLE
Added new FastCGI proxy test case.

### PR DESCRIPTION
**Pull request by dqu123**
Added a new test case. It fails for me; let me know if you spot the problem.

### CODE REVIEW

**Comment by omegaphoenix** [comment]
What is FastCGIConfig doing?  Add a comment and the source if you got the config file from somewhere.  Otherwise, it looks good bro.

**Comment by dqu123** [comment]
It's connecting to a FastCGI proxy server. I'll add the comment. Thanks!

**Comment by omegaphoenix** [comment]
No problem, dude.

**Comment by dqu123** [comment]
Updated.

**Pull request merged**
